baseURL = "https://fungos.github.io/"
languageCode = "en-us"
title = "A Rambling Mind"
copyright = "© Danny Grein"
author = "Danny Grein"
enableRobotsTXT = true
enableEmoji = true
googleAnalytics = "UA-27849510-1"
paginate = 10
footnoteReturnLinkContents = "↩"
theme = "base"
[permalinks]
	post = "/blog/:year/:month/:day/:title/"
	page = "/:filename/"